### ISSUE TITLE
Unable to run the dashboard via docker compose

### ISSUE THREAD

**Issue by Newtoniano** [diogomatoschaves/MyCryptoBot#109]
The Dockerfile for the dashboard microservice doesn't seem to be working. I am using Linux Mint and `docker compose up` gives me the following error:

```
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | > MyCryptoBot-dashboard@0.1.0 start /app
mycryptobot-dashboard-1          | > react-scripts start
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | sh: react-scripts: not found
mycryptobot-dashboard-1          | npm ERR! code ELIFECYCLE
mycryptobot-dashboard-1          | npm ERR! syscall spawn
mycryptobot-dashboard-1          | npm ERR! file sh
mycryptobot-dashboard-1          | npm ERR! errno ENOENT
mycryptobot-dashboard-1          | npm ERR! MyCryptoBot-dashboard@0.1.0 start: `react-scripts start`
mycryptobot-dashboard-1          | npm ERR! spawn ENOENT
mycryptobot-dashboard-1          | npm ERR! 
mycryptobot-dashboard-1          | npm ERR! Failed at the MyCryptoBot-dashboard@0.1.0 start script.
mycryptobot-dashboard-1          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
mycryptobot-dashboard-1          | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | npm ERR! A complete log of this run can be found in:
mycryptobot-dashboard-1          | npm ERR!     /root/.npm/_logs/2023-12-11T19_08_38_716Z-debug.log
```

If I uncomment `RUN npm install react-scripts -g` then I get a similar error saying that typescript is missing, but installing typescript doesn't seem to solve the problem:
```
mycryptobot-dashboard-1          | > MyCryptoBot-dashboard@0.1.0 start /app
mycryptobot-dashboard-1          | > react-scripts start
mycryptobot-dashboard-1          | /usr/local/lib/node_modules/react-scripts/node_modules/resolve/lib/sync.js:113
mycryptobot-dashboard-1          |     throw err;
mycryptobot-dashboard-1          |     ^
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | Error: Cannot find module 'typescript' from '/app/node_modules'
mycryptobot-dashboard-1          |     at Function.resolveSync [as sync] (/usr/local/lib/node_modules/react-scripts/node_modules/resolve/lib/sync.js:111:15)
mycryptobot-dashboard-1          |     at getModules (/usr/local/lib/node_modules/react-scripts/config/modules.js:119:32)
mycryptobot-dashboard-1          |     at Object.<anonymous> (/usr/local/lib/node_modules/react-scripts/config/modules.js:142:18)
mycryptobot-dashboard-1          |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
mycryptobot-dashboard-1          |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
mycryptobot-dashboard-1          |     at Module.load (internal/modules/cjs/loader.js:996:32)
mycryptobot-dashboard-1          |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
mycryptobot-dashboard-1          |     at Module.require (internal/modules/cjs/loader.js:1036:19)
mycryptobot-dashboard-1          |     at require (internal/modules/cjs/helpers.js:72:18)
mycryptobot-dashboard-1          |     at Object.<anonymous> (/usr/local/lib/node_modules/react-scripts/config/webpack.config.js:28:17) {
mycryptobot-dashboard-1          |   code: 'MODULE_NOT_FOUND'
mycryptobot-dashboard-1          | }
mycryptobot-dashboard-1          | npm ERR! code ELIFECYCLE
mycryptobot-dashboard-1          | npm ERR! errno 1
mycryptobot-dashboard-1          | npm ERR! MyCryptoBot-dashboard@0.1.0 start: `react-scripts start`
mycryptobot-dashboard-1          | npm ERR! Exit status 1
mycryptobot-dashboard-1          | npm ERR! 
mycryptobot-dashboard-1          | npm ERR! Failed at the MyCryptoBot-dashboard@0.1.0 start script.
mycryptobot-dashboard-1          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
mycryptobot-dashboard-1          | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | npm ERR! A complete log of this run can be found in:
mycryptobot-dashboard-1          | npm ERR!     /root/.npm/_logs/2023-12-11T19_13_43_114Z-debug.log
mycryptobot-dashboard-1 exited with code 1
```
Not quite sure where the problem lies, if you have any ideas let me know. Thanks in advance

**Comment by diogomatoschaves** [comment]
Hey @Newtoniano. I recently changed that dockerfile to accommodate for the upgrade of my machine to an M2 apple silicon, which potentially creates some issues for intel based machines. Can you try running only with the line:
```shell
RUN npm install -g npm
```

Also, are the other images for the other micro services building with no issues?

**Comment by diogomatoschaves** [comment]
Apologies, I edited my comment after you saw it I guess, I meant `RUN npm install --silent`. This was what was before I made the changes, and it was working correctly. The package.json was not changed. 

The dockerfile before the changes:

```dockerfile
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
ENV DIRECTORY dashboard

# install app dependencies
COPY $DIRECTORY/package.json $DIRECTORY/package-lock.json ./
RUN npm install --silent
#RUN npm install react-scripts -g

# add app
COPY ./$DIRECTORY ./

# start app
CMD ["npm", "start"]
```

**Comment by Newtoniano** [comment]
> Apologies, I edited my comment after you saw it I guess, I meant `RUN npm install --silent`. This was what was before I made the changes, and it was working correctly. The package.json was not changed.
> 
> The dockerfile before the changes:
> 
> ```dockerfile
> FROM node:13.12.0-alpine
> 
> # set working directory
> WORKDIR /app
> 
> # add `/app/node_modules/.bin` to $PATH
> ENV PATH /app/node_modules/.bin:$PATH
> ENV DIRECTORY dashboard
> 
> # install app dependencies
> COPY $DIRECTORY/package.json $DIRECTORY/package-lock.json ./
> RUN npm install --silent
> #RUN npm install react-scripts -g
> 
> # add app
> COPY ./$DIRECTORY ./
> 
> # start app
> CMD ["npm", "start"]
> ```

- This gives the `react-scripts: not found` error. 
- Uncommenting `RUN npm install react-scripts -g
` gives the `Error: Cannot find module 'typescript' from '/app/node_modules'` error. 
- Adding `RUN npm install typescript -g` still gives a typescript not found error.

I'm rebuilding the images every time with no caching using `sudo docker compose build --no-cache && sudo docker compose up` just to be sure, but nothing seems to be working

**Comment by diogomatoschaves** [comment]
Hum I see. Did you change `package-lock.json` locally? With `npm clean-install`, it installs all the dependencies from that file.

**Comment by Newtoniano** [comment]
Obviously not, nothing has been edited. I've exhausted all the very basic solutions to try before opening this. Tomorrow I'll try running it on my intel macbook to see if it runs there at least. Right now I'm using the latest linux mint with the latest docker and docker compose installed, if you'll ever want to reproduce this with a vm. I'll let you know my findings on intel macos, or a solution for linux if I ever find it.

**Comment by diogomatoschaves** [comment]
Yeah the whole point of docker is to avoid these kind of issues, but apparently they still happen... Yeah please let me know your findings. I will also explore some possible solutions.

**Comment by Newtoniano** [comment]
It still seems to be happening on my intel macos, exact same issues, tried `npm install` instead of `npm clean-install` and also tried installing the missing packages without any luck. I will post again if I eventually find a solution.

**Comment by diogomatoschaves** [comment]
Ok, so I've tried also to build everything without cache and it still builds fine on my machine, so there's really no reason why it shouldn't also work for you. 

Now, I've noticed that in the command you mentioned above `sudo docker compose build --no-cache && sudo docker compose up` you use `docker compose` instead of `docker-compose`, so it could be from that. Can you try with `docker-compose up --build`?

Also, if that doesn't work, can you try to build the image separately just using plain docker?

**Comment by diogomatoschaves** [comment]
Ok was reading up and `docker compose` and `docker-compose` should do the same. 

Can you also try to run the start the up locally, i.e. execute the `npm clean-install`and `npm start` commands on your terminal?

**Comment by Newtoniano** [comment]
Very interesting finding, by doing the startup locally with `npm clean-install` then `npm start` I was able to actually run the docker image too!
Now I get these warning, but it works:
```
mycryptobot-dashboard-1          | Compiled with warnings.
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/Dashboard.tsx
mycryptobot-dashboard-1          |   Line 79:6:   React Hook useEffect has a missing dependency: 'updatePipelinesMetrics'. Either include it or remove the dependency array                   react-hooks/exhaustive-deps
mycryptobot-dashboard-1          |   Line 104:6:  React Hook useEffect has missing dependencies: 'previous' and 'updatePipelinesMetrics'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/Menu.tsx
mycryptobot-dashboard-1          |   Line 42:6:   React Hook useEffect has missing dependencies: 'previous' and 'props'. Either include them or remove the dependency array                                                                                                                                                                                                                                                react-hooks/exhaustive-deps
mycryptobot-dashboard-1          |   Line 62:11:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/MenuWrapper.tsx
mycryptobot-dashboard-1          |   Line 3:15:  'Icon' is defined but never used  @typescript-eslint/no-unused-vars
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/MobileMenu.tsx
mycryptobot-dashboard-1          |   Line 3:9:   'Grid' is defined but never used        @typescript-eslint/no-unused-vars
mycryptobot-dashboard-1          |   Line 3:21:  'Transition' is defined but never used  @typescript-eslint/no-unused-vars
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/NewPipeline.tsx
mycryptobot-dashboard-1          |   Line 117:6:  React Hook useEffect has missing dependencies: 'balances', 'pipelines', and 'positions'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
mycryptobot-dashboard-1          |   Line 133:6:  React Hook useEffect has missing dependencies: 'pipelines' and 'previous'. Either include them or remove the dependency array                react-hooks/exhaustive-deps
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/Pipeline.tsx
mycryptobot-dashboard-1          |   Line 6:15:  'RawPipeline' is defined but never used  @typescript-eslint/no-unused-vars
mycryptobot-dashboard-1          |   Line 6:28:  'RawStrategy' is defined but never used  @typescript-eslint/no-unused-vars
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/PipelinePanel.tsx
mycryptobot-dashboard-1          |   Line 153:8:  React Hook useEffect has a missing dependency: 'previous'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/PortfolioChart.tsx
mycryptobot-dashboard-1          |   Line 7:7:   'data1' is assigned a value but never used                                                                                      @typescript-eslint/no-unused-vars
mycryptobot-dashboard-1          |   Line 48:6:  React Hook useEffect has missing dependencies: 'dataProp' and 'pipelineId'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/PositionsPanel.tsx
mycryptobot-dashboard-1          |   Line 65:29:  Expected '===' and instead saw '=='  eqeqeq
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/TradesPanel.tsx
mycryptobot-dashboard-1          |   Line 90:8:  React Hook useEffect has a missing dependency: 'previous'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/components/TradesTable.tsx
mycryptobot-dashboard-1          |   Line 64:6:    React Hook useEffect has a missing dependency: 'trades'. Either include it or remove the dependency array                                                                                                                               react-hooks/exhaustive-deps
mycryptobot-dashboard-1          |   Line 78:6:    React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array                                                                                                                            react-hooks/exhaustive-deps
mycryptobot-dashboard-1          |   Line 85:6:    React Hook useEffect has missing dependencies: 'fetchMoreTrades' and 'page'. Either include them or remove the dependency array. You can also do a functional update 'setPage(p => ...)' if you only need 'page' in the 'setPage' call  react-hooks/exhaustive-deps
mycryptobot-dashboard-1          |   Line 143:28:  Expected '===' and instead saw '=='                                                                                                                                                                                                     eqeqeq
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | src/utils/helpers/index.ts
mycryptobot-dashboard-1          |   Line 55:66:   Expected '===' and instead saw '=='           eqeqeq
mycryptobot-dashboard-1          |   Line 130:20:  eval can be harmful                           no-eval
mycryptobot-dashboard-1          |   Line 162:26:  eval can be harmful                           no-eval
mycryptobot-dashboard-1          |   Line 163:11:  Comparing to itself is potentially pointless  no-self-compare
mycryptobot-dashboard-1          | 
mycryptobot-dashboard-1          | Search for the keywords to learn more about each warning.
mycryptobot-dashboard-1          | To ignore, add // eslint-disable-next-line to the line before.
mycryptobot-dashboard-1          | 
```
Understanding _**why**_ it's like this could be interesting, there is no reason it should work any different if you preinstall locally, as the docker image is supposed to copy the files and do the same thing but only inside the container. Very strange behavior, unfortunately I'm not a node expert at all.

**Comment by diogomatoschaves** [comment]
Found it 🙌

So the reason this was happening was that the declaration of the dashboard app on the `docker-compose.yml` file is mapping a local volume with a volume on the dashboard docker container:

```yaml
volumes:
    - ./dashboard:/app
```

Which was essentially saying that whatever content there is on `app/node_modules` (the container) should be mapped to `dashboard/node_modules` (the local folder), which in case it doesn't exist, makes the app not be able to find the required packages.

This behaviour can be avoided by adding another line:
```yaml
volumes:
    - ./dashboard:/app
    -  /app/node_modules
```

Which tells the container to avoid mapping that specific folder. I'll upload a commit with these changes.

Thanks for making me find this issue!

PS: I'll also try to remove all those warning messages on the frontend 🙈
